### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.70 GiB. GPU

### ISSUE THREAD

**Issue by zhoufy20** [grimmlab/graphxform#1]
Dear Developers of Graphxform,

I hope this message finds you well. I am writing to express my gratitude for the invaluable and effective tool that Graphxform has proven to be in my work. I have encountered an issue：

I am experiencing `a torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.70 GiB. error on my system`, which is equipped with two RTX3090 GPUs. This error is hindering my progress, and I would greatly appreciate any suggestions on how to resolve this matter.

Thank you in advance for your assistance.

Traceback:
```python
Loaded dataset. 367501 molecules with a total of 17860980 datapoints.
---- Loading dataset
  4%|██▊                                                                    | 97/2500 [00:16<06:45,  5.93it/s, batch_loss=5.17]
Traceback (most recent call last):
  File "graphxform/graphxform-main/pretrain.py", line 193, in <module>
    generated_loggable_dict = train_for_one_epoch(
                              ^^^^^^^^^^^^^^^^^^^^
  File "graphxform/graphxform-main/pretrain.py", line 58, in train_for_one_epoch
    logits_zero, logits_one, logits_two = network(input_data)
                                          ^^^^^^^^^^^^^^^^^^^
  File "/home/deroot/miniconda3/envs/graphxform/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deroot/miniconda3/envs/graphxform/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "graphxform/graphxform-main/model/molecule_transformer.py", line 79, in forward
    attn_mask = attn_mask + padding_attn_mask
                ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.70 GiB. GPU
```

**Comment by zhoufy20** [comment]
Optimize Batch Size is ok.

**Comment by johnnycrab** [comment]
Dear zhoufy20,
Thanks for reaching out and we're happy that you like and use the tool! It seems like you've already figured out the issue. Yes, the out of memory errors can happen due to the batch size being too large. It can also help to reduce the number of transformer blocks via `num_transformer_blocks` in `config.py`. Can you tell me where you encountered it, was it during pretraining or when finetuning?
Let me know whenever you need further support!

EDIT: Ah, I see in the traceback that it's during pretraining.

**Comment by zhoufy20** [comment]
Yes, it's during pretraining, I modify the `batch_size` and `num_batches_per_epoch ` is solved.
```python
    batch_size = 64  # Minibatch size. Adjust to your resources. (~32 for 24GB VRAM)
    num_batches_per_epoch = 200  # Number of minibatches per epoch.
```
